# Generated by Django 4.0.3 on 2022-03-21 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_alter_super_super_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_type',
            new_name='super_type_id',
        ),
    ]
