# Generated by Django 4.0.3 on 2022-03-18 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0002_rename_supers_super'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='seconday_ability',
            new_name='secondary_ability',
        ),
    ]
