# Generated by Django 4.0.3 on 2022-03-18 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supers', '0004_alter_super_super_types'),
    ]

    operations = [
        migrations.RenameField(
            model_name='super',
            old_name='super_types',
            new_name='super_type',
        ),
    ]
